name: audio
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.9.1
  - asttokens=2.4.1
  - audioread=3.0.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - cairo=1.18.0
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - comm=0.2.2
  - contourpy=1.3.0
  - cycler=0.12.1
  - dav1d=1.2.1
  - debugpy=1.8.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.3
  - ffmpeg=7.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.54.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.12
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gmp=6.3.0
  - graphite2=1.3.13
  - h2=4.1.0
  - harfbuzz=9.0.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib-resources=6.4.5
  - importlib_resources=6.4.5
  - ipykernel=6.29.5
  - ipython=8.18.1
  - jedi=0.19.1
  - joblib=1.4.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libdeflate=1.22
  - libdrm=2.4.123
  - libedit=3.1.20191231
  - libegl=1.7.0
  - libexpat=2.6.3
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libhwloc=2.11.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopenblas=0.3.27
  - libopenvino=2024.4.0
  - libopenvino-auto-batch-plugin=2024.4.0
  - libopenvino-auto-plugin=2024.4.0
  - libopenvino-hetero-plugin=2024.4.0
  - libopenvino-intel-cpu-plugin=2024.4.0
  - libopenvino-intel-gpu-plugin=2024.4.0
  - libopenvino-intel-npu-plugin=2024.4.0
  - libopenvino-ir-frontend=2024.4.0
  - libopenvino-onnx-frontend=2024.4.0
  - libopenvino-paddle-frontend=2024.4.0
  - libopenvino-pytorch-frontend=2024.4.0
  - libopenvino-tensorflow-frontend=2024.4.0
  - libopenvino-tensorflow-lite-frontend=2024.4.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.44
  - libprotobuf=5.27.5
  - librosa=0.10.2.post1
  - librsvg=2.58.4
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsqlite=3.46.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.4
  - libzlib=1.3.1
  - llvmlite=0.43.0
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mpg123=1.32.6
  - msgpack-python=1.1.0
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numba=0.60.0
  - ocl-icd=2.3.2
  - openh264=2.4.1
  - openjpeg=2.5.2
  - openssl=3.4.0
  - packaging=24.1
  - pandas=2.2.3
  - pango=1.54.0
  - parso=0.8.4
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.2
  - pixman=0.43.2
  - platformdirs=4.3.6
  - pooch=1.8.2
  - prompt-toolkit=3.0.48
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pure_eval=0.2.3
  - pycparser=2.22
  - pydub=0.25.1
  - pygments=2.18.0
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - pysoundfile=0.12.1
  - python=3.9.20
  - python-dateutil=2.9.0
  - python-tzdata=2024.2
  - python_abi=3.9
  - pyzmq=26.2.0
  - qhull=2020.2
  - readline=8.2
  - requests=2.32.3
  - scikit-learn=1.5.2
  - scipy=1.13.1
  - six=1.16.0
  - snappy=1.2.1
  - soxr=0.1.3
  - soxr-python=0.5.0.post1
  - stack_data=0.6.2
  - svt-av1=2.3.0
  - tbb=2021.13.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unicodedata2=15.1.0
  - wayland=1.23.1
  - wayland-protocols=1.37
  - wcwidth=0.2.13
  - x264=1!164.3095
  - x265=3.5
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrender=0.9.11
  - xorg-xorgproto=2024.1
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - appdirs==1.4.4
      - argcomplete==3.6.2
      - asgiref==3.8.1
      - attr==0.3.1
      - attrs==25.3.0
      - azure-core==1.34.0
      - azure-storage-blob==12.25.1
      - black==25.1.0
      - bleach==5.0.1
      - boto==2.49.0
      - boto3==1.38.46
      - botocore==1.38.46
      - cachetools==5.5.2
      - click==8.1.8
      - colorama==0.4.6
      - cryptography==45.0.4
      - datamodel-code-generator==0.26.1
      - defusedxml==0.7.1
      - distro==1.9.0
      - django==4.2.23
      - django-annoying==0.10.6
      - django-cors-headers==3.6.0
      - django-csp==3.7
      - django-debug-toolbar==3.2.1
      - django-environ==0.10.0
      - django-extensions==3.2.3
      - django-filter==2.4.0
      - django-migration-linter==5.2.0
      - django-model-utils==4.1.1
      - django-ranged-fileresponse==0.1.2
      - django-rq==2.5.1
      - django-storages==1.12.3
      - django-user-agents==0.4.0
      - djangorestframework==3.15.2
      - dnspython==2.7.0
      - drf-dynamic-fields==0.3.0
      - drf-flex-fields==0.9.5
      - drf-generators==0.3.0
      - easyocr==1.7.2
      - email-validator==2.2.0
      - expiringdict==1.2.2
      - faker==37.4.0
      - filelock==3.18.0
      - fsspec==2025.5.1
      - genson==1.3.0
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - google-cloud-appengine-logging==1.6.2
      - google-cloud-audit-log==0.3.2
      - google-cloud-core==2.4.3
      - google-cloud-logging==3.12.1
      - google-cloud-storage==2.19.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - grpc-google-iam-v1==0.14.2
      - grpcio==1.73.1
      - grpcio-status==1.73.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - humansignal-drf-yasg==1.21.10.post1
      - ijson==3.4.0
      - imageio==2.37.0
      - inflect==5.6.2
      - inflection==0.5.1
      - isodate==0.7.2
      - isort==5.13.2
      - jinja2==3.1.6
      - jiter==0.10.0
      - jmespath==1.0.1
      - jsf==0.11.2
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - keras==3.12.0
      - label-studio==1.15.0
      - label-studio-sdk==1.0.8
      - launchdarkly-server-sdk==8.2.1
      - lockfile==0.12.2
      - lxml==6.0.0
      - lxml-html-clean==0.4.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - mypy-extensions==1.1.0
      - networkx==3.2.1
      - ninja==1.11.1.4
      - nltk==3.9.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - openai==1.93.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opentelemetry-api==1.34.1
      - ordered-set==4.0.2
      - pathspec==0.12.1
      - proto-plus==1.26.1
      - protobuf==6.31.1
      - psycopg2-binary==2.9.10
      - py-cpuinfo==9.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyboxen==1.3.0
      - pyclipper==1.3.0.post6
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyrfc3339==2.0.1
      - pytesseract==0.3.13
      - python-bidi==0.6.6
      - python-json-logger==2.0.4
      - pytz==2022.7.1
      - pyyaml==6.0.2
      - redis==3.5.3
      - referencing==0.36.2
      - regex==2024.11.6
      - requests-mock==1.12.1
      - rich==14.0.0
      - rpds-py==0.25.1
      - rq==1.10.1
      - rsa==4.9.1
      - rstr==3.2.2
      - rules==3.4
      - s3transfer==0.13.0
      - scikit-image==0.24.0
      - semver==3.0.4
      - sentry-sdk==2.32.0
      - setuptools==80.9.0
      - shapely==2.0.7
      - smart-open==7.1.0
      - sniffio==1.3.1
      - sqlparse==0.5.3
      - sympy==1.14.0
      - tensorflow==2.20.0
      - tensorflow-hub==0.16.1
      - tf-keras==2.20.1
      - tifffile==2024.8.30
      - toml==0.10.2
      - tomli==2.2.1
      - torch==2.7.1
      - torchvision==0.22.1
      - tqdm==4.67.1
      - triton==3.3.1
      - typing-inspection==0.4.1
      - ua-parser==1.0.1
      - ua-parser-builtins==0.18.0.post1
      - ujson==5.10.0
      - ultralytics==8.3.161
      - ultralytics-thop==2.0.14
      - uritemplate==4.2.0
      - urllib3==1.26.20
      - user-agents==2.2.0
      - webencodings==0.5.1
      - wheel==0.40.0
      - wrapt==1.17.2
      - xmljson==0.2.1
